PACKAGENAME="SSH Jump"
MENUNAME="SSH Jump"
APPTYPE="mipsisa32r2el"
APPNAME="sshjump"
APPID=""
LICENSEPAGE="none"
VENDOR="Filipe Brigido"
REQEMBDEVVERSION="2.13"
APPMAJORVERSION="1"
APPMINORVERSION="0"
APPMICROVERSION="0"
APPGRP="sdk"
APPUSR="sdk"
APPOPTS=""
OTHERFILES="bin/sshjump zz_sshjump_proxy.conf postinstall.sh"
SETTINGSPAGEFILE="config.html"
SETTINGSPAGETEXT="SSH Jump terminal"
VENDORHOMEPAGELINK=""
POSTINSTALLSCRIPT="postinstall.sh"
STARTMODE="once"
HTTPCGIPATHS="cgi.txt"
